# Generated by Django 5.0.1 on 2025-11-15 12:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, help_text='Hourly rate in USD', max_digits=8)),
                ('capacity_hours_per_week', models.IntegerField(default=40, help_text='Available hours per week')),
                ('skills', models.JSONField(blank=True, default=list, help_text='List of skills')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'team_members',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
    ]
